### ISSUE TITLE
Use of Coyoneda in the free example

### ISSUE THREAD

**Issue by cdelmas** [johnmcclean-aol/unrestricted-example1#1]
Hi,
In the Free example, you define explicitely a functor instance for Command. I would like to use Coyoneda for that purpose, but I didn't figure out how to do so. How can you do that?

Thanks for any help!

**Comment by johnmcclean** [comment]
Hey Cyril,

Change the static 'lift' methods in Command to return a Free with an embedded Coyoneda instead of a Command. The types become very verbose doing this, but you don't need the functor then.

e.g.

```java
public static Free<µ,String> output(final char a){
       return Free.liftF(new Output<>(a, null), new CommandFunctor());
 }
```
would become 

```java
 public static Free<Higher<Higher<Witness.coyoneda, µ>, String>, String> output(final char a){
        Output<String> o = new Output<String>(a, null);
        Coyoneda<µ, String, String> c = Coyoneda.of(i -> i, o);
        return Free.liftF(c, new Coyoneda.Instances().functor());
        
    }
   
```

Or with static imports

```java
 public static Free<Higher<Higher<coyoneda, µ>, String>, String> output(final char a){
        Output<String> o = new Output<String>(a, null);
        Coyoneda<µ, String, String> c = Coyoneda.of(i -> i, o);
        return Free.liftF(c, new Coyoneda.Instances().functor());
        
    }
   
```

Our program should look someething like this

```java
Free<Higher<Higher<Witness.coyoneda, µ>, String>, Void> program = forEach(output('A'),
                __ -> bell(),
                __ -> output('B'),
                __ -> done());
```


Once we do this for all the commands we can change the type signatures to match in the interpreter, and use the run method on Coyoneda to extract the Command out.

**Comment by cdelmas** [comment]
Very nice, I will try this. Thank you!
