### ISSUE TITLE
add natural transformation example

### ISSUE THREAD

**Issue by jhusain** [johnmcclean-aol/unrestricted-example1#2]
It looks like that the blog post is ongoing. However I was wondering if you were going to provide at least one example of a natural transformation - perhaps to Future?

 I'm  very keen on using Unrestricted for a Haxl-like solution in Java but am unable to  figure out how to write natural transformation to Observable. Unfortunately I don't understand the semantics of visit. Here's my program with the corresponding error, just in case you can spot the issue.

~~~java
public class ObservableInterpreter {

    public static <R> Observable<R> interpret(Unrestricted<R> program){
        /*ERROR: Error:(13, 23) java: incompatible types: inferred type does not conform to equality constraint(s)
inferred: R
equality constraints(s): R,cyclops.control.Unrestricted
*/
        return program.resume(Command.decoder())
                .visit(r -> matchCommand(r), r -> Observable.just(r));
    }
    private static <R> Observable<R> matchCommand(Command<R> command){
        if(command instanceof Command.Done)
            return handleDone((Command.Done<R>)command);
        else if (command instanceof Command.GetVideosCommand)
            return handleGetVideos((Command.GetVideosCommand<Unrestricted<R>>)command);
        throw new IllegalArgumentException("Unknown command " + command);
    }

    static <R> Observable<R> handleGetVideos(Command.GetVideosCommand<Unrestricted<R>> output){
        VideoService videoService = new VideoService();
        // currently mocked
        return output.visit((a, next) -> interpret(next.apply(new Video(23))));
    }

    static <T> Observable<T> handleDone(Command.Done<T> done){
        return Observable.empty();
    }
}
~~~

Any idea what I'm doing wrong?

**Comment by johnmcclean** [comment]
Hey @jhusain, I think I see what the problem is. I used the same type variable (R) for each method, but they are not the same types which I think is confusing things.

In 
```Java
private static <R> Observable<R> matchCommand(Command<R> command)
```
R is likely resolve to something like
```Java
Unrestricted<T>
```
Where T is a different type (defined by R in)

```java
public static <R> Observable<R> interpret(Unrestricted<R> program)
```

If we rename the types in the interpret method, and make the input types to the visit method explicit - I think it makes things a little clearer

```java
public static <T> Observable<T> interpret(Unrestricted<T> program){
        return program.resume(Command.decoder())
                .visit( (Command<Unrestricted<T>> l) -> null, (T r) -> Observable.just(r));
    }
```

This compiles. The problem occurs when we call

```java
matchCommand(l);
```

As the return types of each of the visit do not match

```java
Observable<R> returned from matchCommand and Observable<T> created on the right side of the visit aren't the same thing.
```

The matchCommand method is the core of your interpreter, I would imagine that your interpret method should probably be defined as something like

```java
public static <T,R> Observable<R> interpret(Unrestricted<T> program)
```
Where R is the output of matchCommand (if you can define a concrete type as the result that could be used instead of R). And this should help simplify the logic of your interpret method

```java
public static <T,R> Observable<R> interpret(Unrestricted<T> program){
        return program.resume(Command.decoder())
                .visit( left-> matchCommand(left), right -> ???);
    }
```
Inside interpret we don't know much about T - it's a generic type, and I'm not sure how we can convert it to R (another generic type). T corresponds to the input type of the Function our Functor accepts, which in turn, for non-terminal commands, references the next Command in the program - which means we can't resolve T to a concrete type.

Given we have generic types T and R, and on the right side we have 'T' but need ```Observable<R>``` I would consider just returning ```Observerable.empty()``` here.

```java
public static <T,R> Observable<R> interpret(Unrestricted<T> program){
        return program.resume(Command.decoder())
                .visit( left-> matchCommand(left), right ->Observable.empty());
    }
```
And the method signature for matchCommand should become something like

```java
private static <T,R> Observable<R> matchCommand(Command<T> command)
```

**Comment by jhusain** [comment]
Perfect. Explanation makes complete sense and that resolved my problem. Thanks!
